### PR TITLE
Dependencies & Node Version updates

### PR DESCRIPTION
**Pull request by lb-**
- Update all Package.json dependencies to the latest versions
- Update nvmrc to use Node 18
- Update to Prettier 3.0 (default is now trailing comma all)

### CODE REVIEW

**Comment by lb-** [comment]
@thibaudcolas  mind doing a review on this, just a bit of house cleaning.

**Comment by lb-** [comment]
I should probably update this to be Node 20 as it's now the LTS

**Comment by lb-** [comment]
Updated this PR to now also upgrade to Node 20. This PR can be squashed if needed.

**Comment by lb-** [comment]
Updated this PR to include a few more recent package updates.

**Comment by thibaudcolas** [comment]
Thank you @lb-, all looking good!

**Pull request merged**
